### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jhedrick** [CrossRef/pdfextract#31]
It would seem that it is not possible to run `pdf-extract` from MS Windows as built? Just Googling around didn't yield any promising reasons why this is occurring? Any ideas?

System Configuration:
- Microsoft Windows 8.1 x64 
- Ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32] 
- DevKit-mingw64-64-4.7.2-20130224-1432-sfx
- pdf-extract gem version 0.1.1

Error message:

```
C:\...\ > pdf-extract extract --references .\test2.mask.pdf
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:391:in `block in require_program': program version required (Commander::Runner::CommandError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:390:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:390:in `require_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:52:in `run!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': 126: The specified module could not be found.   - C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libsvm-ru
by-swig-0.4.0/ext/libsvm.so (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libsvm-ruby-swig-0.4.0/lib/svm.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/references/score.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/references/references.rb:3:in `require_relative'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/references/references.rb:3:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:10:in `require_relative'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:10:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/bin/pdf-extract:5:in `require_relative'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/bin/pdf-extract:5:in `<top (required)>'
        from C:/Ruby22-x64/bin/pdf-extract:23:in `load'
        from C:/Ruby22-x64/bin/pdf-extract:23:in `<main>'
```

**Comment by rishabh-joshi** [comment]
Has this issue been resolved?

**Comment by jhedrick** [comment]
Not that I am aware of. I did not try to patch, and have not looked back
into it lately.

## 

Jacob Hedrick
LinkedIn http://www.linkedin.com/in/jacobhedrick | Google+
https://plus.google.com/+JacobHedrick | Calendar
https://www.google.com/calendar/embed?src=jacob.hedrick%40gmail.com&src=stmnji0t28veqobcottlrcfh70@group.calendar.google.com&src=fkbuhuq02gmh2bg9qik5kf1a70@group.calendar.google.com&ctz=America/Chicago&mode=Week&title=Jacob%20Hedrick%27s%20Calendar
