### ISSUE TITLE
Compatibility with current Ruby versions? (CommandError & LoadError)

### ISSUE THREAD

**Issue by sapantha** [CrossRef/pdfextract#33]
Hey,

I recently tried running PDFExtract fresh off Github on a pristine new Ruby on Rails installation (Ruby 2.2.4, Rails 4.2.6), which produced the following errors:

`C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:407:in 'block in require_program': program version required (Commander::Runner::CommandError)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:406:in 'each'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:406:in 'require_program'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:52:in 'run!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in 'run!'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/import.rb:5:in 'block in <top (required)>'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in 'require': 126: Das angegebene Modul wurde nicht gefunden.   - C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libsvm-ruby-swig-0.4.0/ext/libsvm.so (LoadError)
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libsvm-ruby-swig-0.4.0/lib/svm.rb:1:in '<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/references/score.rb:1:in '<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/references/references.rb:3:in 'require_relative'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/references/references.rb:3:in '<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:10:in 'require_relative'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:10:in '<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/bin/pdf-extract:5:in 'require_relative'
        from C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/pdf-extract-0.1.1/bin/pdf-extract:5:in '<top (required)>'
        from C:/RailsInstaller/Ruby2.2.0/bin/pdf-extract:23:in 'load'
        from C:/RailsInstaller/Ruby2.2.0/bin/pdf-extract:23:in '<main>'`

I then tried downgrading to Ruby 1.9.3, but this turned out to be incompatible with some "prawn"-dependency which requires a newer version of Ruby.

What kind of environment will PDFExtract run in?

Thanks,
Basanta

**Comment by AnikoG** [comment]
Hi, it worked for me with ruby 2.0.0
Check my comment in #17
Good luck! : )
