### ISSUE TITLE
font_metrics.rb:42:in `initialize': undefined method `ascent'

### ISSUE THREAD

**Issue by eelcovisser** [CrossRef/pdfextract#4]
I installed pdf-extract using gem install and I'm getting the following error. A change in the library?

Update: downgrading to ruby-1.9.1 does not help

```
$ pdf-extract --trace extract --references --titles d912f50dae928909ed.pdf
/Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/font_metrics.rb:42:in `initialize': undefined method `ascent' for #<PDF::Reader::Font:0x007fc611c82650> (NoMethodError)
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/model/characters.rb:134:in `new'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/model/characters.rb:134:in `block in build_fonts'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/model/characters.rb:131:in `each'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/model/characters.rb:131:in `build_fonts'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/model/characters.rb:163:in `block (2 levels) in include_in'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf.rb:81:in `call'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf.rb:81:in `block (2 levels) in expand_listeners_to_callback_methods'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf.rb:170:in `block in invoke_calls'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf.rb:169:in `each'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf.rb:169:in `invoke_calls'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:42:in `block in parse'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:38:in `each'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:38:in `parse'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/lib/pdf-extract.rb:53:in `view'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/bin/pdf-extract:115:in `block (4 levels) in <top (required)>'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/bin/pdf-extract:112:in `each'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/pdf-extract-0.1.1/bin/pdf-extract:112:in `block (3 levels) in <top (required)>'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/command.rb:180:in `call'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/command.rb:155:in `run'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/runner.rb:402:in `run_active_command'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/runner.rb:78:in `run!'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/delegates.rb:11:in `run!'
        from /Users//.rvm/gems/ruby-1.9.3-p362/gems/commander-4.1.3/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by msegado** [comment]
For the record, afsartori's workaround worked for me on Ubuntu 14.04: I installed prawn 0.12.0 and pdf-reader 1.1.1, uninstalled pdf-reader 1.3.3., and was able to run pdf-extract successfully.
